volumes:
  postgres_test_data:

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8080:3000"
    container_name: api-dev
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - postgres_db
    env_file:
      - ./api/.env.development.local

  postgres_db:
    image: postgres:16-alpine
    ports:
      - "4404:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    env_file:
      - ./api/.env.development.local
    container_name: db-dev
