// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
export default defineConfig({
	schema: "prisma",
	migrations: {
		path: "prisma/migrations",
		seed: "npx tsx prisma/seed.ts", // tergantung runtime yang digunakan, misal jika menggunakan node, maka bisa diganti dengan "npx tsx prisma/seed.js"
	},
	datasource: {
		url: env("DIRECT_URL"),
	},
});
